github: kastldratza # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
#ko_fi: # Replace with a single Ko-fi username
#custom: ["https://www.paypal.me/"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
